// <auto-generated />
using System;
using MakersOfDenmark.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakersOfDenmark.Infrastructure.Migrations
{
    [DbContext(typeof(MODContext))]
    [Migration("20201028191207_MODUsers")]
    partial class MODUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("CategoryTool", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ToolsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("CategoryTool");
                });

            modelBuilder.Entity("MakerSpaceTool", b =>
                {
                    b.Property<Guid>("MakerSpacesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToolsId")
                        .HasColumnType("int");

                    b.HasKey("MakerSpacesId", "ToolsId");

                    b.HasIndex("ToolsId");

                    b.ToTable("MakerSpaceTool");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.MakerSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<int?>("ContactInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VATNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactInfoId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("MakerSpace");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tool");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.User.MODRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MakerSpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MakerSpaceId");

                    b.HasIndex("UserId");

                    b.ToTable("MODRole");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.User.MODUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MODUser");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.User.MODUserFollowMakerSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MakerSpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MakerSpaceId");

                    b.HasIndex("UserId");

                    b.ToTable("MODUserFollowMakerSpace");
                });

            modelBuilder.Entity("CategoryTool", b =>
                {
                    b.HasOne("MakersOfDenmark.Domain.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakersOfDenmark.Domain.Models.Tool", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakerSpaceTool", b =>
                {
                    b.HasOne("MakersOfDenmark.Domain.Models.MakerSpace", null)
                        .WithMany()
                        .HasForeignKey("MakerSpacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakersOfDenmark.Domain.Models.Tool", null)
                        .WithMany()
                        .HasForeignKey("ToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.MakerSpace", b =>
                {
                    b.HasOne("MakersOfDenmark.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("MakersOfDenmark.Domain.Models.ContactInfo", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId");

                    b.HasOne("MakersOfDenmark.Domain.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Address");

                    b.Navigation("ContactInfo");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.Organization", b =>
                {
                    b.HasOne("MakersOfDenmark.Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.User.MODRole", b =>
                {
                    b.HasOne("MakersOfDenmark.Domain.Models.MakerSpace", "MakerSpace")
                        .WithMany()
                        .HasForeignKey("MakerSpaceId");

                    b.HasOne("MakersOfDenmark.Domain.Models.User.MODUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");

                    b.Navigation("MakerSpace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.User.MODUserFollowMakerSpace", b =>
                {
                    b.HasOne("MakersOfDenmark.Domain.Models.MakerSpace", "MakerSpace")
                        .WithMany("Followers")
                        .HasForeignKey("MakerSpaceId");

                    b.HasOne("MakersOfDenmark.Domain.Models.User.MODUser", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId");

                    b.Navigation("MakerSpace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.MakerSpace", b =>
                {
                    b.Navigation("Followers");
                });

            modelBuilder.Entity("MakersOfDenmark.Domain.Models.User.MODUser", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
