name: Continuous deployment 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install EF CLI
      run: |
        dotnet tool install --global dotnet-ef --version 5.0.0-rc.1.20451.13
        dotnet tool restore
    - name: Install dependencies
      run: dotnet restore MakersOfDenmark.WebAPI.sln
    - name: Build
      run: dotnet build MakersOfDenmark.WebAPI.sln --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release -o dotnetcorewebapp --no-build
    - name: Migrate Database
      run: dotnet ef migrations script --idempotent --project ./src/MakersOfDenmark.Infrastructure -s ./src/MakersOfDenmark.WebAPI -o migration
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEPLOY_CREDENTIALS }}
    - uses: azure/sql-action@v1
      with:
        server-name: REPLACE_THIS_WITH_YOUR_SQL_SERVER_NAME
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: './migration.sql'
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: makersofdenmark 
        publish-profile: ${{secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}
        package: './dotnetcorewebapp' 
